[package]
name = "fabric-challenge"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
rand_core = "0.9.2"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "sumcheck_bench"
harness = false
